### ISSUE TITLE
Use sessions SELECT resource model for unbooked sessions

### ISSUE THREAD

**Issue by mecha** [RebelCode/rcmod-eddbk-rest-api#21]
Use the [`unbooked_sessions_select_rm`](https://github.com/RebelCode/rcmod-wp-bookings-cqrs/blob/develop/src/Module/WpBookingsCqrsModule.php#L254) instead of the `sessions_select_rm` as the sessions resource model for the sessions controller. This makes the REST API only provide sessions that do not conflict with existing (non-cart) bookings.

**Comment by markzahra** [comment]
Available sessions are not visible in either the Nedit Booking modal or the Booking Wizard since this change was made.

**Comment by mecha** [comment]
The cause for that is related to another package. An issue has been [opened here](https://github.com/RebelCode/sql-expression-renderer/issues/2). Closing.
