### ISSUE TITLE
Fix default value handling in CQRS controllers

### ISSUE THREAD

**Issue by mecha** [RebelCode/rcmod-eddbk-rest-api#4]
## Symptoms

The REST API responds with as `500 Server Error`.

## How to Reproduce

In EDD Bookings:
- Navigate to the bookings list or calendar page
- Create or edit a booking
- Open your browser dev tools
- Find the Networking panel
- Clear the payment number field in the booking modal, leaving it empty
- Clear the Networking panel log
- Save the booking
- An entry should appear in the Networking panel for a REST API request
- After some time, the response should come back with a `500` status code

For further validation:
- Click the entry and find the Response (or "Preview" in Chrome) panels
- There should be an error message that reads: _"Not a stringable value"_

## Possible Cause

If an empty value present in the request, it will be normalized to `null`. This results in errors since the values are attempted to be normalized to strings when the SQL query is being generated.

## The Solution

Add null value handling for values accepted in CQRS controllers. Each value should have a meaningful default that can be stringified and is a valid SQL query value.

**Comment by markzahra** [comment]
No instructions provided on how to test this issue/fix.

**Comment by mecha** [comment]
@markzahra Amended description. From what I could tell, PR #5 fixed this issue. The steps outlined in the description should now help you confirm the fix.

**Comment by markzahra** [comment]
@mecha tomorrow please speak to me to make sure I ran the test correctly.
