### ISSUE TITLE
Bookings don't transition on update

### ISSUE THREAD

**Issue by mecha** [RebelCode/rcmod-eddbk-rest-api#6]
Bookings must be able to transition on update, similar to how they perform an initial transition on creation.

**Comment by markzahra** [comment]
From what I can tell, this has not been implemented in Alpha 2.

While testing, opening an Edit Booking modal and changing the status via the Actions does not yet work. The status remains the same.

**Comment by mecha** [comment]
It seems that the EDD Bookings UI JS is still sending the incorrect status codes. I tried to schedule a booking and the transition sent was `scheduled`, which is the status name *not* the transition name.

**Comment by markzahra** [comment]
Possibly related to https://github.com/orgs/RebelCode/projects/2#card-9858340

**Comment by mecha** [comment]
@romalytvynenko @markzahra I think this is actually related to the `rebelcode/rcmod-wp-bookings-ui` module. Therefore, I propose we close this issue and convert the existing project card into an issue for that module.

**Comment by romalytvynenko** [comment]
This is related to booking-js, creating new issue.

**Comment by romalytvynenko** [comment]
Can be closed, I opened the new issue: https://github.com/RebelCode/bookings-js/issues/16

**Comment by mecha** [comment]
Great 👍 Closing this issue

**Comment by markzahra** [comment]
Issue being moved to UAT since there is a new issue created for this problem.

**Comment by XedinUnknown** [comment]
When a new issues is created for the same problem, please remember to link this issue.
